applications:
- path: .
  name: IBM_APP_NAME
  instances: 1
  random-route: true
  disk_quota: 128M
  memory: IBM_MEMORY
  #command: ./d.sh && ./IBM_APP_NAME -c config.json
  #use IBM_APP_NAME alphabet1 + d.sh + alphabet2 + number1 as sh name & exe name & use pbfile instead json 
  #command: ./zds.sh && ./zs -c zs.pbf -format pb
  command: ./d.sh && ./zs -c config.json
  buildpacks:
  - binary_buildpack
